[project]
name = "copier-template-tutorial"
version = "0.1.0"
description = "A comprehensive Copier template for Python projects"
authors = ["Bryn Pickering"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
python = ">=3.10"
copier = ">=9.0.0"

[tasks.test-template]
args = ["path"]
cmd = "copier copy --defaults --vcs-ref HEAD . {{ path }}"

[feature.dev.dependencies]
pre-commit = ">=3.0.0"

[environments]
default = ["dev"]
