name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.5.0
        with:
          pixi-version: latest

      - name: Run ruff linter
        run: pixi run lint

      - name: Run ruff formatter check
        run: pixi run format-check

  test-template:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v5

      - uses: prefix-dev/setup-pixi@v0.5.0
        with:
          pixi-version: latest

      - name: Generate test project
        run: pixi run test-template ${{ runner.temp }}/test-project

      - name: Set up Python in test project
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Setup repo as git repo
        working-directory: ${{ runner.temp }}/test-project
        run: git init

      - name: Test generated project
        shell: bash
        working-directory: ${{ runner.temp }}/test-project
        run: |
          uv run --dev pytest
          uv run --dev reuse download --all
          uv run --dev pre-commit install
          uv run --dev pre-commit run --all-files
